export const SET_LAUNCH_DATA = 'SET_LAUNCH_DATA'

export const SET_VERTICAL_LIST_DATA = 'SET_VERTICAL_LIST_DATA'

export const SET_TRACK_LIST_ID = 'SET_TRACK_LIST_ID'

export const SET_THEME = 'SET_THEME'

export const SET_TRACK_PLAYER = 'SET_TRACK_PLAYER'
export const SET_TRACK_STATUS = 'SET_TRACK_STATUS'
export const SET_TRACK_DISPLAY = 'SET_TRACK_DISPLAY'
export const SET_TRACK_QUEUE_AND_CURRENT = 'SET_TRACK_QUEUE_AND_CURRENT'
export const SET_TRACK_INDEX = 'SET_TRACK_INDEX'
export const SET_TRACK_PLAY_STATUS = 'SET_TRACK_PLAY_STATUS'

export const FETCH_LYRICS = 'FETCH_LYRICS'
export const FETCH_LYRICS_SUCCESS = 'FETCH_LYRICS_SUCCESS'
export const FETCH_LYRICS_FAILED = 'FETCH_LYRICS_FAILED'
export const SET_LYRICS = 'SET_LYRICS'