export const SET_LAUNCH_DATA = 'SET_LAUNCH_DATA'

export const SET_VERTICAL_LIST_DATA = 'SET_VERTICAL_LIST_DATA'

export const SET_TRACK_LIST_ID = 'SET_TRACK_LIST_ID'

export const SET_THEME = 'SET_THEME'

export const SET_TRACK_PLAYER_DATA = 'SET_TRACK_PLAYER_DATA'

export const FETCH_LYRICS = 'FETCH_LYRICS'
export const FETCH_LYRICS_SUCCESS = 'FETCH_LYRICS_SUCCESS'
export const FETCH_LYRICS_FAILED = 'FETCH_LYRICS_FAILED'
export const SET_LYRICS = 'SET_LYRICS'

export const SET_ACTIVE_NAV = 'SET_ACTIVE_NAV'


export const SET_USER_DATA = 'SET_USER_DATA'

export const SET_SONG_STATE = 'SONG_STATE'


export const SET_FETCH_TRACK="SET_FETCH_TRACK"

export const SET_FAVOURITE_SONG ="SET_FAVOURITE_SONG"